# Generated by Django 4.2.3 on 2023-07-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditemnutrient",
            name="food_item",
        ),
        migrations.RemoveField(
            model_name="fooditemnutrient",
            name="nutrient",
        ),
        migrations.DeleteModel(
            name="FoodItem",
        ),
        migrations.DeleteModel(
            name="FoodItemNutrient",
        ),
        migrations.DeleteModel(
            name="Nutrient",
        ),
    ]
